// Code generated by mockery v2.53.6. DO NOT EDIT.

package repository

import (
	models "todo-app-backend/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockITodoRepository is an autogenerated mock type for the ITodoRepository type
type MockITodoRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: todo
func (_m *MockITodoRepository) Create(todo *models.Todo) error {
	ret := _m.Called(todo)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Todo) error); ok {
		r0 = rf(todo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *MockITodoRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: page, limit, search, filterBy, filterValue
func (_m *MockITodoRepository) GetAll(page int, limit int, search string, filterBy string, filterValue string) ([]models.Todo, int64, error) {
	ret := _m.Called(page, limit, search, filterBy, filterValue)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Todo
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(int, int, string, string, string) ([]models.Todo, int64, error)); ok {
		return rf(page, limit, search, filterBy, filterValue)
	}
	if rf, ok := ret.Get(0).(func(int, int, string, string, string) []models.Todo); ok {
		r0 = rf(page, limit, search, filterBy, filterValue)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, string, string, string) int64); ok {
		r1 = rf(page, limit, search, filterBy, filterValue)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(int, int, string, string, string) error); ok {
		r2 = rf(page, limit, search, filterBy, filterValue)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: id
func (_m *MockITodoRepository) GetByID(id int) (*models.Todo, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Todo, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Todo); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ToggleComplete provides a mock function with given fields: id
func (_m *MockITodoRepository) ToggleComplete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for ToggleComplete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: todo
func (_m *MockITodoRepository) Update(todo *models.Todo) error {
	ret := _m.Called(todo)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Todo) error); ok {
		r0 = rf(todo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockITodoRepository creates a new instance of MockITodoRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITodoRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITodoRepository {
	mock := &MockITodoRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
